---

  - name: install pip requirements
    pip: requirements=/vagrant/requirements.txt virtualenv=/vagrant/venv

  - name: hide login message
    copy: dest=/home/vagrant/.hushlogin
          content=
          owner=vagrant
          group=vagrant
          mode=0644

  - name: install bash_profile
    copy: src=dot.bash_profile
          dest=/home/vagrant/.bash_profile
          owner=vagrant
          group=vagrant
          mode=0644

  - name: create env.sh file
    # Since /vagrant is mounted over NFS, we don't know the exact uid and gid
    # of the actual user on the host machine. Need to use sudo_user
    sudo_user: vagrant
    template: src=env.sh.j2
              dest=/vagrant/env.sh
              mode=0600

  - name: run migrations
    command: /vagrant/venv/bin/python /vagrant/manage.py db upgrade chdir=/vagrant
    environment:
        SQLALCHEMY_DATABASE_URI: postgresql://{{database.username}}:{{database.password}}@localhost:5432/{{database.name}}
