from update_ratebeer import update_ratebeer
from update_polet import update_pol_beers
from update_pol_shops import read as update_pol_shops
from update_pol_stock import update_pol_stock
from update_adminareas import update_adminareas
