---
- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- name: copy configuration files
  template: src={{app.name}}.ini.j2
            dest=/etc/uwsgi/apps-available/{{app.name}}.ini
            owner=root
            group=root
            mode=0600
  notify:
    - restart uwsgi

- name: enable apps
  file: src=/etc/uwsgi/apps-available/{{app.name}}.ini
        dest=/etc/uwsgi/apps-enabled/{{app.name}}.ini
        owner=root
        group=root
        state=link

  notify:
    - restart uwsgi

- name: make sure uwsgi is running
  service: name=uwsgi state=running enabled=yes
