---
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: install nb language-pack
    apt: pkg=language-pack-nb state=latest

  - name: Set timezone variables
    copy: content='Europe/Oslo\n'
              dest=/etc/timezone
              owner=root
              group=root
              mode=0644
    notify:
          - update timezone

  - name: install ntp
    apt: pkg=ntp state=latest

  - name: make sure ntp is running
    service: name=ntp state=running enabled=yes